#!/bin/bash
set -xe
export CLASSPATH=$(for i in /build/org.rulez.magwas.zenta.editor.build/target/products/Zenta/win32/win32/x86_64/Zenta/plugins/*; do printf "%s:" $i; done;echo /home/developer/lib/randoop-4.2.3/randoop-all-4.2.3.jar)
java -cp $CLASSPATH:/build/org.rulez.magwas.zenta.model/bin randoop.main.Main help gentests |less
project=org.rulez.magwas.zenta.model
package=${project}.handmade
class=ZentaDiagramModel

slashed_package=$(echo $package|sed 'sA\.A/Ag')
#prefix=${project}.tests/src/${slashed_package}
prefix=
#mkdir -p $prefix

java -cp $CLASSPATH:/build/org.rulez.magwas.zenta.model/bin randoop.main.Main gentests --testclass=$package.$class --error-test-basename=${class}ErrorTest --regression-test-basename=${class}RegressionTest --junit-package-name=${package}

