#!/bin/bash
set -xe
export DISPLAY=:0
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
Xvnc :0&
cp toolchains.xml ~/.m2
make zentaworkaround
cp sonar-settings.xml ~/.m2/settings.xml
mkdir -p ./org.rulez.magwas.zenta.integrationtests/generated-images
mvn install
git checkout -b build
dch -D $BRANCH -v 1.0-1.$BRANCH.$BUILD_NUMBER commit $(git rev-parse HEAD)
git add --all :/
git commit -m  "debian build"
make recording
debuild -us -uc
git checkout $BRANCH
