#!/bin/bash
set -xe
VERSION=$(cat VERSION)
export DISPLAY=:0
sudo Xvnc :0&
sleep 1 ;reset
cp toolchains.xml ~/.m2
make zentaworkaround
mkdir -p ./org.rulez.magwas.zenta.integrationtests/generated-images
mvn install
git checkout -b build-$(date +%s)
echo|dch --force-distribution -D kodekonveyor -v $(git describe --tags) commit $(git rev-parse HEAD)
git add --all :/
git commit -m  "debian build"
#make recording
DEB_BUILD_OPTIONS=noautodbgsym debuild -rfakeroot -us -uc
mkdir -p target
mv ../zenta* target
mv org.rulez.magwas.zenta.editor.build/target/products/* target
#make stoprecording
#git checkout $BRANCH
