#!/bin/bash
set -xe
sed -i 'sA<version.*package versionA<version>'"$(git describe --tags)"'</version><!--package versionA' pom.xml
export DISPLAY=:0
sudo Xvnc :0&
cp toolchains.xml ~/.m2
make zentaworkaround
cp sonar-settings.xml ~/.m2/settings.xml
mkdir -p ./org.rulez.magwas.zenta.integrationtests/generated-images
mvn install
git checkout -b build-$(date +%s)
dch --force-distribution -D $BRANCH_NAME -v $(git describe --tags) commit $(git rev-parse HEAD)
git add --all :/
git commit -m  "debian build"
make recording
debuild -rfakeroot -us -uc
cp ../*.deb target
#git checkout $BRANCH
