#!/bin/bash
set -xe
branch=$(echo ${TRAVIS_BRANCH}|sed 'sA/A-Ag')
mkdir -p shippable

for arch in linux.gtk.x86_64 linux.gtk.x86 macosx.cocoa.x86_64 win32.win32.x86_64 win32.win32.x86
do
    cp org.rulez.magwas.zenta.editor.build/target/products/Zenta-${arch}.zip shippable/Zenta-${branch}-${arch}.zip
done

scp shippable/*.zip magwas,zenta@frs.sourceforge.net:/home/pfs/project/z/ze/zenta/unstable
