#!/bin/bash
set -x
make stoprecording
branch=$(echo ${TRAVIS_BRANCH}|sed 'sA/A-Ag')
mkdir -p shippable
cp /tmp/record.flv shippable

find -type f -name '*.zip'
for arch in linux.gtk.x86_64 macosx.cocoa.x86_64 win32.win32.x86_64
do
    cp org.rulez.magwas.zenta.editor.build/target/products/Zenta-${arch}.zip shippable/Zenta-${branch}-${arch}.zip
done

scp shippable/*.zip magwas,zenta@frs.sourceforge.net:/home/pfs/project/z/ze/zenta/unstable
rsync -e "ssh -p 22022" -ar ../zenta_* shippable@demokracia.rulez.org:/var/www/repos/apt/debian/incoming
